# Generated by Django 5.0.6 on 2024-06-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="expenditure",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
