# Generated by Django 5.0.6 on 2024-06-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_sale_expenditure"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="capacity",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
