# Generated by Django 5.0.6 on 2024-06-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_restaurant_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="pka",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
